name: build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: |
            21
            25
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x ./gradlew
      - run: ./gradlew --no-daemon --no-configuration-cache --max-workers=1 -Dorg.gradle.jvmargs=-Xmx4g :fabric_26_2:build -x test
      - uses: actions/upload-artifact@v4
        with:
          name: enchantment-custom-table-fabric-26.2
          path: fabric_versions/26.2/build/libs/
